name: Lint and Test

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Instalar dependencias de desarrollo
          pip install -r requirements_dev.txt

      - name: Lint with Ruff
        run: |
          ruff .

      - name: Run tests with pytest
        run: |
          pytest tests/